behaviors:
  EscapeArtist:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 16384             # Reduced to allow for more frequent updates
      learning_rate: 3e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.995
        strength: 0.02
    max_steps: 250000                # Further reduced to allow for faster checkpoints
    time_horizon: 2000
    summary_freq: 500
