behaviors:
  EscapeArtist:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096              # Increase batch size for larger updates
      buffer_size: 400000           # Adjust buffer size for the larger batch
      learning_rate: 5e-4           # Maintain steady learning rate
      beta: 0.001                   # Lower entropy for less exploration
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 512
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 2.5
    max_steps: 50000000
    time_horizon: 20000
    summary_freq: 10000             # Reduce frequency of summaries for long training
    threaded: true

engine_settings:
  width: 800
  height: 600
  quality_level: 0
  time_scale: 100                  # Increase time scale for faster simulation
  target_frame_rate: -1
  capture_frame_rate: 60

environment_parameters:
  difficulty:
    sampler_type: constant
    sampler_parameters:
      value: 0
    default_value: 0
