behaviors:
  EscapeArtist:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 500000
      learning_rate: 1e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory:
        memory_size: 256
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.5
    max_steps: 25000000
    time_horizon: 512
    summary_freq: 2000
    threaded: true
    self_play:
      save_steps: 15000
      play_against_latest_model: true
      team_change: 75000
      swap_steps: 2000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1000.0
