behaviors:
  EscapeArtist:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048          # Increased from 1024
      buffer_size: 20480        # Increased from 10240
      learning_rate: 3e-4
      beta: 5e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5e6
    time_horizon: 1000          # Adjusted from 64 to 1000
    summary_freq: 1000
