behaviors:
  EscapeArtist:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128  # Keep or increase to 128 if you want to experiment with more stable updates
      buffer_size: 4096  # Keep or increase to 4096 if you increase batch_size
      learning_rate: 1.0e-4  # Reduced learning rate to stabilize learning with reward changes
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256  # Keep at 256 for complex environments
      num_layers: 3  # Keep at 3 for deeper learning in complex scenarios
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000000  # You can keep this very high if you plan to train for a long time
    time_horizon: 256  # Increased for longer episodes; consider 128 or 256
    summary_freq: 5000  # This is good for TensorBoard tracking
    keep_checkpoints: 5
