behaviors:
  EscapeArtist:
    trainer_type: sac
    hyperparameters:
      buffer_init_steps: 1000
      buffer_size: 50000
      learning_rate: 3e-4
      learning_rate_schedule: constant
      batch_size: 512
      tau: 0.005
      steps_per_update: 10
      save_replay_buffer: false
      init_entcoef: 0.2
      reward_signal_steps_per_update: 10
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    threaded: true
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 2000
