behaviors:
  EscapeArtist:
    trainer_type: ppo_new
    hyperparameters:
      batch_size: 512
      buffer_size: 50000           # Reduced to allow for more frequent updates
      learning_rate: 3e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000             # Further reduced to allow for faster checkpoints
    time_horizon: 128
    summary_freq: 2000
